### ISSUE TITLE
OBO release versions are not legal obo due to lack of declarations

### ISSUE THREAD

**Issue by dosumis** [obophenotype/xenopus-phenotype-ontology#21]
OBO format files should declare subsets and synonym types.  

Merging imports into the OBO release file has lead to OBO files that lack some of these declarations.

e.g. xpo.obo 

has
```yaml
[Term]
id: CHEBI:24431
name: chemical entity
namespace: chebi_ontology
def: "A chemical entity is a physical entity of interest in chemistry including molecular entities, parts thereof, and chemical substances." []
subset: 3_STAR
synonym: "chemical entity" EXACT [UniProt]
```

but the subset is not declared in the header 

This prevents consumption by a number of legacy tools.  I suspect this is a general ODK release issue, possibly stemming from ROBOT filtering.  It may prevent adoption of complete ODK release pipeline by some resources using legacy OBO loaders. 

CC @matentzn
